In [1]:
#numpy is a library to store multidimenional array 

#Why we prefer numpy over lists
# *Lists are slow while the numpy are fast because numpy uses the fixed type

In [4]:
import numpy as np

In [11]:
#How to initialize array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#how to initalize 2-D array and so on.....
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)


[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension 
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get Shape
b.shape

(2, 3)

In [8]:
a.shape

(3,)

In [13]:
# Get Type
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('float64')

In [14]:
a = np.array([1,2,3], dtype='int16')

In [15]:
a.dtype

dtype('int16')

In [19]:
# Get Size
a.itemsize

2

In [20]:
b.itemsize

8

In [21]:
# Get total size
a.nbytes

6

In [22]:
b.nbytes

48

In [23]:
# Get number of elements
a.size

3

In [24]:
b.size

6

In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
c = np.array([[4,7,5,3,6],[1,0,6,4,7],[3,6,4,9,2]])

In [27]:
print(c)

[[4 7 5 3 6]
 [1 0 6 4 7]
 [3 6 4 9 2]]


In [28]:
# Get a specific element [r, c]
a[1, 5]

13

In [29]:
c[2,2]

4

In [30]:
c[1,1]

0

In [31]:
# Get a specific row 
a[0, :]    # ':' 

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [34]:
c[0,:]

array([4, 7, 5, 3, 6])

In [35]:
c[2,:]

array([3, 6, 4, 9, 2])

In [36]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [37]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [38]:
a[0,1:-2:1]

array([2, 3, 4, 5])

In [39]:
a[0,3:5:1]

array([4, 5])

In [40]:
a[0,3:4:1]

array([4])

In [42]:
#Change the oroginal value from array
a[1,5] = 20

print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [47]:
a[:,2] = [5,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [48]:
#3-D Example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
# Get specific element (work outside in)
b[0,1,1]

4

In [52]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [53]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((4,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [60]:
# Any other number
np.full((2,2), 99)
np.full((3,3),55)

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [61]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [62]:
np.full_like(b,3)

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

In [63]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.5740194 , 0.50067636],
       [0.75718378, 0.87721291],
       [0.88778982, 0.12791855],
       [0.98778208, 0.68467435]])

In [64]:
np.random.random_sample(a.shape)

array([[0.70756958, 0.80620531, 0.39038477, 0.46743393, 0.9498444 ,
        0.36619172, 0.2574635 ],
       [0.56357649, 0.2264071 , 0.13699023, 0.58174276, 0.4001185 ,
        0.87822835, 0.66863599]])

In [65]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 6,  0,  2],
       [-2,  4,  5],
       [ 5, -4, -1]])

In [66]:
np.random.randint(4,8, size=(3,3))

array([[5, 4, 5],
       [4, 6, 5],
       [5, 6, 5]])

In [67]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [69]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
#Mathematics Opertions


a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
a+2

array([3, 4, 5, 6])

In [8]:
a - 2

array([-1,  0,  1,  2])

In [9]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [6]:
a*2

array([2, 4, 6, 8])

In [11]:
b = np.array([1,0,1,0])
print(b)

[1 0 1 0]


In [12]:
a+b

array([2, 2, 4, 4])

In [13]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [14]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [15]:
np.tan(b)

array([1.55740772, 0.        , 1.55740772, 0.        ])

In [16]:
#Linear Algebra

In [18]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [21]:
a*b  #Multiplication not possible due to not same number of row and columns

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [20]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [22]:
#Statistics

In [23]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.min(stats)

1

In [29]:
np.max(stats)


6

In [30]:
np.max(stats, axis=1) #axis gives the max of value of all 


array([3, 6])

In [31]:
np.max(stats, axis=0) # 0 axis gives the complete line

array([4, 5, 6])

In [32]:
np.sum(stats)

21

In [33]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [34]:
np.sum(stats, axis=1)

array([ 6, 15])

In [35]:
###Reorganizing Arrays

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [37]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [40]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [41]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [45]:
#Data From File

filedata = np.genfromtxt("E:\Special\Online Work\data.txt.txt", delimiter=',')
print(filedata)

[[  1.   2.   4.   6.   3.   4.   2.   7.   9.  24.   6.   8. 234.  45.]
 [  3.   5.   7.   9. 434.   7.   3.   5.   3.   5.   7.   4.   8.   1.]
 [  2.   4.   7.   9.   0.   4.  21.   2.  34.   5.   7.  98.  64.   8.]]


In [46]:
filedata = np.genfromtxt("E:\Special\Online Work\data.txt.txt", delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1   2   4   6   3   4   2   7   9  24   6   8 234  45]
 [  3   5   7   9 434   7   3   5   3   5   7   4   8   1]
 [  2   4   7   9   0   4  21   2  34   5   7  98  64   8]]


In [47]:
#Boolean

In [48]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True,  True, False]])

In [49]:
filedata[filedata > 50]

array([234, 434,  98,  64])

In [50]:
np.all(filedata > 50)

False

In [51]:
np.any(filedata > 50)

True

In [52]:
np.any(filedata > 50 , axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True, False])

In [53]:
(((filedata > 50) & (filedata < 100)))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True,  True, False]])

In [54]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False, False,  True]])